# Generated by Django 4.1.7 on 2023-04-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_body_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-coment_date',)},
        ),
        migrations.AddField(
            model_name='post',
            name='categry',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
