# Generated by Django 4.2 on 2023-05-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_commentsysteme_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsysteme',
            options={'ordering': ('-coment_date',)},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
