# Generated by Django 4.2 on 2023-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_commentsysteme_options_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsysteme',
            name='coment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
