# Generated by Django 4.2 on 2023-05-01 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_commentsysteme_coment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsysteme',
            name='coment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
