# Generated by Django 4.2 on 2023-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_content2_post_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
