# Generated by Django 4.2 on 2023-05-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_contactus_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
    ]
