# Generated by Django 4.2 on 2023-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_contactus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
