# Generated by Django 4.2 on 2023-05-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_contactus_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
